### ISSUE TITLE
Source and originator

### ISSUE THREAD

**Issue by JLRishe** [SteelsenS/ASpace_Questions#13]
I think this may be more of a question for @R-Klingenberger than for @SteelsenS, but regarding these two fields, this is what Steelsen said in the Gist:

Regarding Source Location:

> DRMS populates this.

I am guessing that Source would correspond to the values listed in the Source tab of the Master Tables Config form ("Acquisitions", "Arts Library") and the dropdown at the top of the Import form. Is there any actual action item for me regarding storing Source somewhere? It looks like that's already firmly embedded in the Import form.

Regarding Originator:

> Master Tables Config based on source

So would this be a new field that is associated with each individual source? Or stored some other way?

**Comment by R-Klingenberger** [comment]
Jimmy,

Sorry for my ambiguity.

In Master Tables Config, there is currently a table for “Source”. It is a nice, short, informal indication of which part of the larger library system sent an item to Preservation. Since that is the first thing asked by the Import form, it can be leveraged by the form’s search/retrieval logic and the rules.

“Originator” is the name of a field specified by the metadata rules we will follow for the creation of the preservation master files. This is essentially the same as “Source”, but should include the more formal name of the part of the library system that sent us the item.

I think the simplest solution is to add a second column to the Source Table which will be editable text and can be changed to what we want to appear as “Originator”.

For example: Where Source = Arts Library; Originator = Robert B. Haas Family Arts Library.

I think “Source” already has a database field where it is maintained (as opposed to simply displayed by a form or two), so I don’t think that has an action item for you. The creation of a second column in the Source table called Originator and the use of that field value in the appropriate forms and passing that on when we get to vendors in the CSV report when we start modifying the Shipment Form would be the action item for both the remaining issues.

Let me know if that answers the remaining questions.

Regards,

Robert

~~~~~~~~~~~~~~~~~~~~~~~~~~~
Robert Klingenberger
Head, Digital Reformatting & Microfilming Services
Preservation Department, 344 Winchester Avenue
203-432-1715
For Collections related Emergency at YUL: 203-530-5414

From: Jimmy Rishe [mailto:notifications@github.com]
Sent: Thursday, December 21, 2017 11:05 AM
To: SteelsenS/ASpace_Questions <ASpace_Questions@noreply.github.com>
Cc: Klingenberger, Robert <robert.klingenberger@yale.edu>; Mention <mention@noreply.github.com>
Subject: [SteelsenS/ASpace_Questions] Source and originator (#13)


I think this may be more of a question for @R-Klingenberger<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Dklingenberger&d=DwMCaQ&c=cjytLXgP8ixuoHflwc-poQ&r=3K24tgxQnXaXuivGoYfOcHQ6oNa_V4uR6Re0wuWaYHg&m=nH3HiSi0gPJLAN5BNwWbE6XsUQg0-xKtacuW8B5JjhY&s=mcYU7h1gaSd1kWD0Bqq1-9K4K7VK4uyx6xUFwcljzL0&e=> than for @SteelsenS<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_steelsens&d=DwMCaQ&c=cjytLXgP8ixuoHflwc-poQ&r=3K24tgxQnXaXuivGoYfOcHQ6oNa_V4uR6Re0wuWaYHg&m=nH3HiSi0gPJLAN5BNwWbE6XsUQg0-xKtacuW8B5JjhY&s=ARNowSDhF5FWS0Q6kM_rqBoWmuI7_OoxC4AXl0xmpzw&e=>, but regarding these two fields, this is what Steelsen said in the Gist:

Regarding Source Location:

DRMS populates this.

I am guessing that Source would correspond to the values listed in the Source tab of the Master Tables Config form ("Acquisitions", "Arts Library") and the dropdown at the top of the Import form. Is there any actual action item for me regarding storing Source somewhere? It looks like that's already firmly embedded in the Import form.

Regarding Originator:

Master Tables Config based on source

So would this be a new field that is associated with each individual source? Or stored some other way?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SteelsenS_ASpace-5FQuestions_issues_13&d=DwMCaQ&c=cjytLXgP8ixuoHflwc-poQ&r=3K24tgxQnXaXuivGoYfOcHQ6oNa_V4uR6Re0wuWaYHg&m=nH3HiSi0gPJLAN5BNwWbE6XsUQg0-xKtacuW8B5JjhY&s=2PqbRFhaeUlOzMb-IO_52BN-lpB4vX7c_693tYyt6Oo&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ag5Gz3HxXe5VEgM0biepWFqtXGS7VT6Uks5tCoGjgaJpZM4RKBUT&d=DwMCaQ&c=cjytLXgP8ixuoHflwc-poQ&r=3K24tgxQnXaXuivGoYfOcHQ6oNa_V4uR6Re0wuWaYHg&m=nH3HiSi0gPJLAN5BNwWbE6XsUQg0-xKtacuW8B5JjhY&s=xlSXTGMSIxrSPkz34kHV1PjsijoMha9VnDQgzp74jCc&e=>.

**Comment by JLRishe** [comment]
Confirmed with Robert over GoToMeeting:

- Need to add Originator to Master Table Config
- Within the Item Import form:
   - We need to load this value
   - Show it along with the item data (when the item is from ASpace)
   - Include the value in certain calculated values (Header Metadata Description)
